import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideSkewRecovery } from '@skewkit/angular-router';
import { provideSkewData } from '@skewkit/angular-data';
import { provideSkewWorkflow } from '@skewkit/angular-workflow';
import { appRoutes } from './app.routes';
import { manifestUrl } from './simulator';

/**
 * App 1's identity.
 *
 * Normally generated by `skew-stamp` at build time; pinned here so the demo's
 * scenarios are reproducible. `builtAt` is what lets the probe *order* two
 * builds — and ordering is the difference between "reload fixes this" and
 * "reload loops forever".
 */
export const BUILD_IDENTITY = {
  buildId: 'app-one-0.1.123',
  builtAt: '2026-08-07T10:00:00.000Z',
} as const;

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(appRoutes),

    provideSkewRecovery({
      identity: BUILD_IDENTITY,
      // Swapped by the simulator to fake an origin that is behind us.
      manifestUrl: manifestUrl(),
      // Left at the default 'reload-at-target'. The guard rails in front of it
      // are what the demo is actually showing off.
      retryAttempts: 1,
      retryDelayMs: 120,
    }),

    provideSkewData({
      persistOutbox: true,
      buildId: BUILD_IDENTITY.buildId,
      onOutboxError: (message, detail) => console.warn('[outbox]', message, detail),
    }),

    provideSkewWorkflow({
      buildId: BUILD_IDENTITY.buildId,
      onDraftError: (message, detail) => console.warn('[draft]', message, detail),
    }),
  ],
};
